---
output: html_document
  
---

# Introduction

Many humanitarian and development organizations produce large amounts of data as part of their operations. UNHCR (the United Nations High Commissioner for Refugees, also known as the UN Refugee Agency) is no exception. As an output of a collaboration with the World Bank, much of the household survey data that UNHCR collects on the well-being and living conditions of refugees and internally displaced persons is now accessible through UNHCR microdata. The analysis of this data, which can provide hitherto inaccessible insight into the lives of those who have been forcibly displaced, can inform research, humanitarian operations, development programs and the development of policy. However, without a formal system of microdata citation, there is currently limited shared visibility into the outputs generated from this data.

Understanding UNHCR microdata use in more depth will have three principal benefits. First, it will allow for a more comprehensive assessment of the impact of data production and dissemination. Second, it would generate insight into which kinds of data are being used most effectively, and this information could be used to inform data collection and dissemination strategies. Third, it could be used to refine the ways in which data is made discoverable and accessible.
