# Proposed Solution
Our proposed solution is an automated process which generates outputs at two levels.

## Dataset-level outputs

* List of citing papers
* Distribution of fields of study
* Distribution of nature of use

## Library-level outputs

* Network of citing authors
* Network of citing disciplines


```{note}
Citing disciplines depend on categories defined by external institutions.
```

We hope that this approach will provide value to multiple stakeholders, such as: 

| **Audience** 	| **Benefit** 	|
|---	|---	|
| UNHCR/ GDS Microdata Curation Team 	| Automated procedure saves time and identifies citations that would otherwise be missed, and usage statistics will give the team objective information on which datasets are useful 	|
| UNHCR Operations 	| Usage statistics and network analysis may illuminate usage gaps (e.g. additional fields that would be helpful to include in surveys) 	|
| Prospective MDL users 	| Tool can provide insight into how our data has been used in the past (and thus what is possible for their own work) 	|


